### ISSUE TITLE
Scala Behavior Changes Make Some Examples Fail

### ISSUE THREAD

**Issue by hellerim** [deanwampler/programming-scala-book-code-examples#131]
Many command line utilities which call other programs use "--" to separate arguments to these programs from the preceding  arguments which are consumed by the respective utility itself. Scala and sbt obviously adopted this behavior. This is why on p. 16 ff, in particular on p.18 below, examples fail at least with Scala 3.5.0 and sbt 1.10.1, e.g.
`$ scala -cp . -M progscala3.introscala.UpperMain1 hello computed world!`
now should read
`$ scala -cp . -M progscala3.introscala.UpperMain1 -- hello computed world!`,
otherwise you should expect lots of _input file not found_ exceptions.
Since it took me quite a while to figure out the cause of these exceptions - I'm not an sbt or scala expert -, I think this new behavior should be made known in some prominent place. (?)

**Comment by deanwampler** [comment]
Thanks for letting me know and sorry the examples didn't work "out of the box"! I'll add some warning language about "evolving changes" to the README and fix all the examples this coming week.
