### ISSUE TITLE
Rename repo to "prog-scala-2nd-3rd-ed-code-examples"

### ISSUE THREAD

**Issue by deanwampler** [deanwampler/programming-scala-book-code-examples#25]
The repo `master` branch has been tracking Scala 2.13 and library changes. The book-compatible versions of the repo are tagged. Hence, I don't see any reason not to continue using this repo for the forthcoming 3rd edition. Hence, renaming would make that clear.

**Comment by SethTisue** [comment]
how about just `prog-scala-code-examples` then :-)

**Comment by deanwampler** [comment]
That's crazy talk!!

Yeah, that's better. The original repo was called something like that, but it's pretty much dead.

**Comment by deanwampler** [comment]
Okay, since I gain a few characters by deleting `2nd-edition`, it's now `programming-scala-book-code-examples`.
