### ISSUE TITLE
for-validations-good.sc should add import scalaz.Validation.FlatMap._

### ISSUE THREAD

**Issue by byejude** [deanwampler/programming-scala-book-code-examples#28]
code in // src/main/scala/progscala2/forcomps/for-validations-good.sc

when i ran this script,my console told me "value flatMap is not a member of scalaz.Validation[List[String],Int]", and i checked ur sbt.build,and i found the scalaz`s version is 7.27
 and i checked the scalaz source code,i found this : 
` /** Import this if you wish to use `flatMap` */
  object FlatMap {
    @inline implicit def ValidationFlatMapRequested[E, A](d: Validation[E, A]): ValidationFlatMap[E, A] =
      new ValidationFlatMap(d)
  }`
so i just add  add import scalaz.Validation.FlatMap._ and finally i ran script sucessfully

**Comment by deanwampler** [comment]
Thanks for the report. I'll update the code this weekend.

**Comment by deanwampler** [comment]
I just pushed a fix to the master branch with this import added. Thanks again for the bug report.
