### ISSUE TITLE
parallel.sc should bu updated

### ISSUE THREAD

**Issue by byejude** [deanwampler/programming-scala-book-code-examples#29]
source in // src/main/scala/progscala2/collections/parallel.sc
should add 'import scala.collection.parallel.CollectionConverters._',see it in [scala-parallel-collections](https://github.com/scala/scala-parallel-collections),
and when i import this in parallel.sc and run it, it says 
'error: value par is not a member of scala.collection.immutable.Range.Inclusive
       did you mean map, max, or span?
'
and i change it to *.scala and add main function,it runs sucessful, and i dont know why

**Comment by byejude** [comment]
bu -> be

**Comment by deanwampler** [comment]
Closing this now as the code has been completely refactored.
