### ISSUE TITLE
sbt test fails for wrong LANG

### ISSUE THREAD

**Issue by grisuji** [deanwampler/programming-scala-book-code-examples#39]
Hi :-) 
in the very beginning of the book (3rd edition), Chapter 1, Building the Code Examples, the recommended `sbt test` fails in case you have the wrong LANG set. In my case it was set to "de_DE.UTF-8" and the tests failed with:
```
[info] Passed: Total 7, Failed 0, Errors 0, Passed 7
[error] Failed: Total 233, Failed 7, Errors 0, Passed 226
[error] Failed tests:
[error]         progscala3.fp.combinators.PayrollSuite
[error]         progscala3.fp.curry.TupledFuncSuite
[error]         progscala3.dsls.payroll.PayrollSuite
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 2 s, completed 31.07.2021, 16:56:39
```
After changing it with 
`export LANG="en_US.UTF-8" `

the tests  run  successfull. 
Would be nice to have this mentioned in a short note, because it  took me a few hours to find the reason. 

Greetings 
Grisuji

**Comment by deanwampler** [comment]
Curious! I tried `export LANG="de_DE.UTF-8; sbt test` and it worked fine, but that just mean it doesn't always "respect" the setting. I'll add a troubleshooting note to the README. Sorry you wasted a few hours on this, but thanks for reporting it.

**Comment by deanwampler** [comment]
I pushed an update to the `README`.

**Comment by deanwampler** [comment]
@grisuji I just merged PR 42, https://github.com/deanwampler/programming-scala-book-code-examples/pull/42, which should fix this issue. Let me know if you still have problems.
